### ISSUE TITLE
How to use it with pandoc

### ISSUE THREAD

**Issue by nirname** [sprin/markdown-inline-graphviz#4]
Can't figure out how to use it with Pandoc. Now I'm using similar script via pandoc filters. When I am trying to [activate extension](http://pandoc.org/MANUAL.html#non-pandoc-extensions) like that `markdown+inline_graphviz`, I get the following error
```
pandoc: Unknown extension: inline_graphviz
```
What I am doing wrong?

**Comment by sprin** [comment]
Hi Nikolay,

This was written as an extension for [Python-Markdown](https://pythonhosted.org/Markdown/index.html), not for Pandoc. It's possible to make a similar extension for Pandoc.

I would be happy to take the opportunity to learn a bit more Haskell if someone could sponsor a few hours of the work (BTC, Ethereum, Monero accepted). Even small amounts would be greatly appreciated.

**Comment by PeterJCLaw** [comment]
One approach to Pandoc might be to use it as a [pandoc filter](http://pandoc.org/filters.html). Granted it's not quite as neat as having it directly as a language extension, but it might be easier to get going as there's already good support for [python filters](https://github.com/jgm/pandocfilters).
